name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via SSH
        run: |
          ssh root@172.21.21.108 "
            cd /var/www/htmlrunner &&
            git fetch origin &&
            git reset --hard origin/main
          "
